### ISSUE TITLE
update remote naming conventions

### ISSUE THREAD

**Issue by trentgill** [monome/crow#135]
See #132 

`^^id` should return `^^id(...)`

need consistent names for the input lib callbacks. currently `ret_cv` and `change` are obviously random and not good. i'll add a list of all the default callback names here shortly and we can make decisions. these changes will need to propogate through the norns & max code as well.

**Comment by tehn** [comment]
- [x] firmware rename
- [ ] max update
- [ ] maxforlive update (?)

**Comment by trentgill** [comment]
@tehn was trying to salvage what i could from m4l patch, but i think it's built for ableton10, and i've only got 9 installed on this comp. will have to wait til next time.
