### ISSUE TITLE
Ansible (via ii) channels are 0-based

### ISSUE THREAD

**Issue by mimetaur** [monome/crow#197]
I noticed this today when I connected my new Crow (via Norns) and Ansible. It took me a while to debug why nothing was working, until I happened to notice the channel two light flashing. 

Seems to me everything in Lua should stay 1-based, even if it just means making an offset by 1 in the Ansible definition on the Crow side.

**Comment by tehn** [comment]
thanks for catching this. will fix--- it's a bug in the ansible.lua ii definition

**Comment by ngwese** [comment]
Ah yes, and I've confirmed just now - this off by one issue was mentioned in #198 as well. That ticket is looking at enhancements to the ii definition system so I'll keep this issue in mind.

**Comment by trentgill** [comment]
fixed in #224
