### ISSUE TITLE
Max4Live ->crow object

### ISSUE THREAD

**Issue by trentgill** [monome/crow#20]
jason needs it.

**Comment by trentgill** [comment]
Should be a MIDI Effect so the MIDI TRS input can be used to play an Ableton instrument.

**Comment by whimsical-sam** [comment]
Saying hi for trent!

**Comment by trentgill** [comment]
- [ ] Generic usb-port autoselection
OSX ports are of the form: `usbmodem14*1` and windows `COM*`
