### ISSUE TITLE
Alert user if i2c lines are low & suggest activating pullups

### ISSUE THREAD

**Issue by trentgill** [monome/crow#247]
The low level detection of this already exists in ll/i2c.c (in HAL_I2C_ErrorCallback), but it only prints to the debugger.

Should plumb this back to the lib/ii.c driver which should call to the caw library to show up for the user via usb.

**Comment by simonvanderveldt** [comment]
Would be nice to have this. I forgot to enable the pullups and was scratching my head why it didn't work :grimacing:
