### ISSUE TITLE
i2c support multiple same-devices

### ISSUE THREAD

**Issue by trentgill** [monome/crow#255]
At present, only TXi and er301 have support for multiple units. They both implement it in different ways: TXi uses ascending channel indexes. [1,4]=first device, [5-8]=second device. er301 adds 100 to the command to point to the second device.

I want to move toward a unified syntax for working with multiple devices (and one that feels natural in the lua env). This represents a slight departure from the teletype ops. I'm adding multiple JF unit support in the forthcoming update, so that device (and W/ shortly) will be added to this list, so i think a single syntax is important.

Syntax proposal:
```lua
-- current syntax. remains & always talks to the first / default address
ii.jf.trigger()

-- proposed new syntax. nb: only works if the device supports multiple devices
ii.jf[1].trigger() -- identical to above, but *required* when using multiple devices
ii.jf[2].trigger() -- speaks to the second defined address
```

To add support, the only change required in the i2c descriptor should be:
```lua
-- current. keep this for devices that only support one address
i2c_address = 0x70

-- proposed for muti-address capable devices
i2c_address = {0x70, 0x75} -- a list of addresses, in the order they will be indexed
```

**Comment by tehn** [comment]
really into this approach.
