### ISSUE TITLE
global reset

### ISSUE THREAD

**Issue by tehn** [monome/crow#28]
command to RESET crow

- clear/reset global state `_G` to startup condition (pre flash execution = blank slate)
- stop metros
- reset ADC and DAC activity, midi state, etc

**Comment by trentgill** [comment]
should this be another version of `^^reset`. that currently just reboots the microcontroller (so obviously resets `_G`), but stops crow from executing flash?

perhaps there could be a lua function to set a 'don't run flash' bit?

that would work if the lua environment is working fine, but is this functionality meant for a non-responsive system-state? unsure what the intended use-case is.

**Comment by tehn** [comment]
i can't rationalize my original reasoning for needing this... i was thinking too norns-like.

existing `^^reset` is great. if a script needs to be bypassed it should just be cleared via `^^clear` first. my general feeling is that the crow's flash should not be precious. it's always going to be on disk in some editor somewhere.
