### ISSUE TITLE
Failures in init() not reported

### ISSUE THREAD

**Issue by ngwese** [monome/crow#280]
Using the released version 1.0.2 firmware I've noticed that runtime errors which occur within the `init()` function are not reported (in druid).

The lack of error reporting gives rise to hard to diagnose bugs due to the silent early termination of the `init()` function.

Reproduction steps:
- Create `init_fail.lua` with the following contents:
```
reset = true

function init()
  print("init start")
  reset(true)
  print("init end")
end

```
- Create `toplevel_fail.lua` with the following contents:
```
reset = true

function my_init()
  print("init start")
  reset(true)
  print("init end")
end

my_init()
```
- In `druid` run `r init_fail.lua` and compare that to `r toplevel_fail.lua`

The expected behavior is that failures which occur in `init()` when invoked by the firmware are reported.

**Comment by trentgill** [comment]
Will investigate this for 1.0.4 - thanks for the easy repro script :)
