### ISSUE TITLE
After a `r` from druid, crow reports the wrong script as 'running'

### ISSUE THREAD

**Issue by trentgill** [monome/crow#283]
See: https://llllllll.co/t/crow-help-druid/25864/184

Basically issue is after an `r` command from druid, crow restarts the lua VM and prints the 'current script'. At present the `r` command is run directly from RAM, versus a regular boot which reads from flash.

Need to add an extra case for when the module 'restarts' but is running a script in RAM, and thus read the script name from that RAM buffer.

**Comment by csboling** [comment]
Should the full contents of the RAM script be shown, like with uploaded scripts, or just the title? What should be shown after running a script from RAM when another script is already uploaded to flash? Show both scripts? Show just the title of the most recently run one?
