### ISSUE TITLE
reset lua environment after new user script received

### ISSUE THREAD

**Issue by trentgill** [monome/crow#33]
currently, the script is just loaded, and would require a hard reset to stop existing code.

**Comment by trentgill** [comment]
@tehn do you have a reference to the norns codebase that describes what happens when a new script is loaded? i'm guessing it's mostly to do with stopping metros, but perhaps also resetting to some defaults?

easiest solution would be to soft-reset the device after a new script is received. this would likely cause a tiny 'blip' in the outputs, and probably reset them to some static voltage. personally i like the idea that an ongoing ASL would finish it's slope even after the new script was loaded. then the user script could define initial output values should it so desire.

i'm thinking the next logical step up would be a lua VM reset, so it wouldn't fully restart the device, but it would close the entire lua VM, and reinitialize it just like when the device turns on (including loading the script stored in flash).

this means we don't need to worry about all the different bundles of state that have to be re-init'd, but rather we just abandon the old environment and make a new one.

**Comment by tehn** [comment]
norns script reset is much more complex procedure given the management of other processes (crone/supercollider/etc) and the state of a full menu system and screens/etc.

i'd just reset the hardware. a tiny blip on the outputs would not be a dealbreaker given flashing a new script is a development process, not live performance.

i like the idea of elegant completion of slopes, so we can leave this issue open but i'm going to remove the v1 milestone

**Comment by tehn** [comment]
so just to be clear, it's up to the editor (or REPL) to manually reset the crow after an upload and i'm ok with that

**Comment by trentgill** [comment]
i think it's fine to have editor/REPL manually reset. it's totally possible that someone wants to upload a script that *isn't* an `init` script, but rather is a set of helper functions that should be called by the editor/REPL -- in that case there's no need for a reset as userscript is autoloaded in Lua after upload.
