### ISSUE TITLE
wsyn.lua docs

### ISSUE THREAD

**Issue by dndrks** [monome/crow#344]
fm index accepts -5 to +5, not 0 to +5:
https://github.com/monome/crow/blob/2348ecb01ff8603e3fb483a1235ba305d77337b0/lua/ii/wsyn.lua#L56

ramp == sawtooth, right?:
https://github.com/monome/crow/blob/2348ecb01ff8603e3fb483a1235ba305d77337b0/lua/ii/wsyn.lua#L50

values below 0 seem to behave the same as 0:
https://github.com/monome/crow/blob/2348ecb01ff8603e3fb483a1235ba305d77337b0/lua/ii/wsyn.lua#L68

**Comment by trentgill** [comment]
fixed in #342
