### ISSUE TITLE
norns core.crow.ii_actions.html autogenerated docs missing

### ISSUE THREAD

**Issue by tyleretters** [monome/crow#361]
<img width="1392" alt="Screen Shot 2020-11-13 at 16 30 26" src="https://user-images.githubusercontent.com/1298097/99127321-a1529780-25cd-11eb-814e-84a5775880db.png">

**Comment by trentgill** [comment]
@tyleretters any idea what i need to do to fix this? i just auto-generate the code from the `ii` descriptors but paid no mind to how it appears for the doc generator.

**Comment by tehn** [comment]
this can be fixed over at the docs repo.

won't be a good auto-solution unless the auto-generator adds ldoc strings (basically, `--- function-name` before each function) but that probably doesn't make total sense for this lib
