### ISSUE TITLE
refine calibration engine

### ISSUE THREAD

**Issue by trentgill** [monome/crow#39]
- [x] add lua hook to print the current calibration values
- [x] add lua hook to recalibrate the io
- [x] print a warning over TTY saying to make sure no cables attached. also upon success
- [x] add zero-check for second input channel (currently just copied from adc0 )
- [x] test accuracy of v8 once we have real CV examples running
- [x] add bounds checks to confirm the data is correct. return error to lua if not (could be a cable attached)
- [x] as it only happens in factory, increase timing, add delays for settling time, make it more robust

**Comment by trentgill** [comment]
Still work to be done!
As of #156 the measurements are:

Listed are mV delta from expected value at (-3, 0, 3, 7) volts
Input 1:
- Output[1] = (-19,-5,4,14)
- Output[2] = (-20,-5,3,14)
- Output[3] = (-19,-5,4,15)
- Output[4] = (-20,-5,4,15)
Input 2:
- Output[1] = (-7,0,8,17)
- Output[2] = (-8,0,7,17)
- Output[3] = (-7,0,7,18)
- Output[4] = (-2,1,3,7)

As can be seen the 'zeroing' of Input 2 is more accurate than Input 1. Input 2 is near perfect & it's ground reference for offset testing is a direct connection to ground through switched jack. Input 1 on the other hand measures it's ground reference via the MUX508 & a 330r resistor. We can assume the ON resistance of the MUX and 330r are causing the discrepancy and need to be factored out somehow.

The discrepancy in Output[4] across the 2 input channel measurements is confounding. Perhaps due to a measurement error? Perhaps something weird with the routing on the pcb? Seems strange that for input[1] the output[4] measurement is near identical to the rest, but output[4] seems off only on input[2]. These measurements were doubly-confirmed though.

The scaling is clearly not being calculated correctly. For input[1] all outputs have between 33 & 35mV differential between -3 & 7V. This differential is evenly distributed across the 4 measurements, so doesn't seem to be caused by non-linearity, but is just an error in the calculation of the scaling factor. Similarly the input[2] measurements show a similar differential (though only 24-25mV excluding the output[4] outlier). Currently input[2] just copies the scaling factor from input[1] as there is no in-built mechanism to test for this without manually patching. Even though the scaling is incorrect, in practice it still seems far better to copy the inaccurate scaler from input[1] than to use the calculated values (which give >50mV differential).

Perhaps the engine could be rebuilt to run the tests recursively, in a gradient descent style. Adjusting the actually used values until the measured values are what is expected. Currently the tests are based on known input/output pairs, and calculating offsets based on the measured delta to expected result. Perhaps there is something missing in the algorithm to correctly calculate this.

Process notes:
Of note, the scaling is measured first for both ins & outs. This is done by using the 'shift' variable to store a reference 'zero' and then a known test-level saved into 'scale'. The difference is calculated & used to determine the scaling factor required to stretch appropriately. This value is set in the driver, so that when the test process continues, the scaling factor has already been applied (ie factored out of the offset calculation).
Then the 'shift' variable is recalculated based on the 'zero'. Then it is applied to the driver.
The ADCs are done first, using a ground reference, and the highly accurate 2v5 reference of the ADC chip (which the DAC & output buffers use as reference).
After the ADCs are finished calibrating, the approach is repeated for the outputs, using Input[1] as the test case, via the internal MUX508 chip which selects the source to send to the input.

There may be some interaction i'm not understanding with how these values are being applied in the driver.
ADC: `sample = (readValue * scalar) + shift`
DAC: `output = (outValue + shift) * scalar`
I believe this is the correct of applying the transformations, but maybe they're backward?

Would love help on this!

**Comment by tehn** [comment]
> I believe this is the correct of applying the transformations, but maybe they're backward?

yes this was slightly tricky logic to follow. have you tried flipping them as a dumb test?

> something weird with the routing on the pcb?

i'm going to take a look but that would be quite surprising

**Comment by trentgill** [comment]
I've been testing on a single unit only so far. Probably worthwhile to see what the numbers are like across an array of crows, in order to confirm that the above observations are universal.

Do you remember what order the the '0V' offset issue on teletype was? Mostly wondering whether -5mV offset at 0V is going to upset people. Further, if it's *always* -5mV regardless of module, I can just hack in an extra offset on input[1] until we figure out the root cause. Same goes for the scaling being a little too high.

**Comment by tehn** [comment]
how many crow units do you have? i can send down a few if needed. and of course i can also run numbers on a few more units.

**Comment by trentgill** [comment]
fixed in #397
