### ISSUE TITLE
clock.sync(x) where x > 1 does not sync correctly to beats

### ISSUE THREAD

**Issue by fardles** [monome/crow#437]
(as discussed briefly with @trentgill on the crow study discord)

When clock.sync() is given a beat value of more than 1, it does not sync correctly to beats, but tends to resume the coroutine (a) too soon; and (b) as a result, too quickly the next time round. This leads to two resumptions in very quick succession. This is very clearly demonstrated with the use of `sequins`, although it has been confirmed that the issue arises even without `sequins` being called. This has been tested at "normal" tempos of =< 120bpm.

Example script (to be run directly on crow):

```
s = sequins

test = s{0,6,12,18}

test_function = function()
    while true do
        clock.sync(10)
        print(test())
        print(clock.get_beats())
    end
end

clock.run(test_function)
```

Expected behaviour: `0`, `6`, `12`, `18` are printed at regular intervals (here, 10 beats). 

Behaviour: 

```
0
310.0
6
319.984
12
320.0
18
329.984
0
330.0
6
339.984
12
340.0
18
349.984
...
```

In the above, there are pairs of numbers printed in quick succession, which is not the expected behaviour. As can be seen, after every whole beat (e.g. 330), the next resumed coroutine is earlier (e.g. 339.984), which then leads to an almost immediate resumption on the whole beat (e.g. 340). 

This has been tested with other `clock.sync()` values. [Here is a gist](https://gist.github.com/fardles/dcc21ca9481a3c9ce093b79299af18ba) with the other results for `clock.sync(4)`, `clock.sync(2)`, `clock.sync(1)` and `clock.sync(1/2)`. The same issues arises where the value for `clock.sync()` is more than 1.

**Comment by daveriedstra** [comment]
More discussion of probably related symptoms is happening on lines: https://llllllll.co/t/crow-v3/46425/250

Basically, when syncing to values from a sequins, eg `clock.sync(my_seq())`, crow performs the following combinations of sequins patterns and tempi incorrectly:

- `s{3, 3, 2}` at `clock.tempo = 216` produces a 3 - 2 - 1 pattern
- `s{1, 1, 2/3}` at `clock.tempo = 216` produces a 1 ⅓ - 1 - ⅔ pattern
- `s{1, 1, 2/3}` at `clock.tempo = 72` produces a 1 ⅔ - 1 - ⅓ pattern

The clock doesn't seem to be resuming the coroutine earlier as in @fardles 's test case, but it *does* resume on the whole beat. Additionally, `s{1, 1, 2/3}` is performed differently at the different tempi. Printouts of the beat values are given in the lines thread.
