### ISSUE TITLE
^^append command

### ISSUE THREAD

**Issue by trentgill** [monome/crow#48]
add functionality to append to an existing user-script, rather than requiring the whole thing to be uploaded at once. this way a user can extend their script on the fly without having to worry about the full script.

maybe this is not a good idea?

**Comment by tehn** [comment]
seems a little tricky to have a build-as-you-go script and expect it to run correctly on next boot. i don't see the need necessarily.

but i was thinking about a way to send a bigger chunk for runtime execution (not stored to flash) ie a longer multiline function. not sure how the current REPL works with incomplete functions etc submitted line by line.

**Comment by trentgill** [comment]
agreed it's tricky and probably unnecessary. my thinking was that the behaviour would be the same as typing directly into the VM. thus if you defined a function, it would actually load both then overwrite the previous.

realistically, anybody writing a complex enough script where this is relevant is probably writing a traditional file on the host, or deliberately using crow as a live-coding environment.

as to your second point, i've made a separate issue for improving the repl here: #58
