### ISSUE TITLE
update lua module names to better parallel norns

### ISSUE THREAD

**Issue by trentgill** [monome/crow#59]
currently crowlib treats the modules themselves with first character uppercase (eg: Input, Output, Metro), while the user-space objects use lower case (eg: input, output, metro).

**Comment by tehn** [comment]
i think the current behavior is perfect. nobody is going to actually use the uppercase libs in a user script--- they're just for initialization in the core lib.

so the naming conventions (vs norns) are very similar from the user perspective.

we're overhauling a bunch of the norns core stuff anyway, likely stashing initializers into an obfuscated subtable (`_norns` or something)... so i think the approaches are similar.

the only setback of global `Output` is that someone might overwrite it with their own script. which i guess doesn't matter a whole lot given the execution order at boot?

i'm going to close this but we can continue discussion if needed?
