### ISSUE TITLE
Windows DFU-util can't open device

### ISSUE THREAD

**Issue by whimsical-sam** [monome/crow#90]
Issue: 
`./dfu-util -l`
returns error:
`Cannot open DFU device 0483:df11`

Solution: 

1. Download [Zadig](https://zadig.akeo.ie/).
2. Put Crow into Bootloader
3. Opened Zadig.
4. Select Zadig>list all devices.
5. Select crow: `dfu bootloader` from dropdown menu
6. Current driver should say `STTub30 (v3.0.4.0)`
6. Select `WinUSB (v6.1.7600.16385)` as replacement driver.
7. Click `Replace Driver`

---

Issue:  `,0483:df11` causes powershell to fail on comma syntax
Solution: ` ','0483:df11`

**Comment by csboling** [comment]
Believe this is now included [here](https://github.com/monome/docs/blob/gh-pages/crow/update.md#windows)
